'use client';

import { MoreHorizontal, PlusCircle, Trash2, Wand2, LoaderCircle } from "lucide-react";
import { useEffect, useState, useTransition } from "react";
import { collection, getDocs, addDoc, deleteDoc, doc } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { useToast } from "@/hooks/use-toast";
import { generateWidgetHtml } from "@/ai/flows/widget-generator-flow";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Skeleton } from "@/components/ui/skeleton";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog"

interface Widget {
    id: string;
    name: string;
    description: string;
    html: string;
    config: {
        type: 'category' | 'tag';
        value: string;
        limit: number;
    }
}

interface Category {
    id: string;
    name: string;
}

export default function WidgetsPage() {
    const [widgets, setWidgets] = useState<Widget[]>([]);
    const [loading, setLoading] = useState(true);
    const { toast } = useToast();
    
    // Dialog state
    const [isDialogOpen, setIsDialogOpen] = useState(false);
    const [isSaving, startSavingTransition] = useTransition();
    
    // Form state
    const [newWidgetName, setNewWidgetName] = useState("");
    const [newWidgetDescription, setNewWidgetDescription] = useState("");
    const [newWidgetHtml, setNewWidgetHtml] = useState("");
    const [newWidgetConfigType, setNewWidgetConfigType] = useState<'category' | 'tag'>('category');
    const [newWidgetConfigValue, setNewWidgetConfigValue] = useState("");
    const [newWidgetConfigLimit, setNewWidgetConfigLimit] = useState(5);

    // Categories for select dropdown
    const [categories, setCategories] = useState<Category[]>([]);
    const [loadingCategories, setLoadingCategories] = useState(true);

    // AI state
    const [isGenerating, setIsGenerating] = useState(false);


    const fetchWidgetsAndCategories = async () => {
        setLoading(true);
        setLoadingCategories(true);
        try {
            const widgetsCollection = collection(db, "widgets");
            const widgetsSnapshot = await getDocs(widgetsCollection);
            const widgetsData = widgetsSnapshot.docs.map(doc => ({
                id: doc.id,
                ...doc.data()
            })) as Widget[];
            setWidgets(widgetsData);

            const categoriesCollection = collection(db, "categories");
            const categoriesSnapshot = await getDocs(categoriesCollection);
            const categoriesData = categoriesSnapshot.docs.map(doc => ({
                id: doc.id,
                ...doc.data() as { name: string }
            }));
            setCategories(categoriesData);

        } catch (error) {
            console.error("Error fetching data:", error);
            toast({ variant: 'destructive', title: 'Error', description: 'Could not fetch widgets or categories.' });
        } finally {
            setLoading(false);
            setLoadingCategories(false);
        }
    };

    useEffect(() => {
        fetchWidgetsAndCategories();
    }, []);
    
    const resetForm = () => {
        setNewWidgetName("");
        setNewWidgetDescription("");
        setNewWidgetHtml("");
        setNewWidgetConfigType("category");
        setNewWidgetConfigValue("");
        setNewWidgetConfigLimit(5);
    }

    const handleGenerateHtml = async () => {
        if (!newWidgetDescription.trim()) {
            toast({ variant: 'destructive', title: 'Error', description: 'Please provide a description for the AI.' });
            return;
        }
        setIsGenerating(true);
        try {
            const result = await generateWidgetHtml({ description: newWidgetDescription });
            setNewWidgetHtml(result.html);
            toast({ title: 'Success', description: 'HTML generated by AI.' });
        } catch (error) {
            console.error("Error generating widget HTML:", error);
            toast({ variant: 'destructive', title: 'AI Error', description: 'Could not generate HTML.' });
        } finally {
            setIsGenerating(false);
        }
    };
    
    const handleAddWidget = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!newWidgetName.trim() || !newWidgetHtml.trim() || !newWidgetConfigValue.trim()) {
            toast({ variant: 'destructive', title: 'Error', description: 'Please fill out all required fields.' });
            return;
        }

        startSavingTransition(async () => {
            try {
                await addDoc(collection(db, "widgets"), {
                    name: newWidgetName,
                    description: newWidgetDescription,
                    html: newWidgetHtml,
                    config: {
                        type: newWidgetConfigType,
                        value: newWidgetConfigValue,
                        limit: newWidgetConfigLimit,
                    }
                });
                toast({ title: 'Success', description: 'Widget created successfully.' });
                resetForm();
                setIsDialogOpen(false);
                fetchWidgetsAndCategories();
            } catch (error) {
                console.error("Error adding widget:", error);
                toast({ variant: 'destructive', title: 'Error', description: 'Could not create widget.' });
            }
        });
    };
    
    const handleDeleteWidget = async (widgetId: string) => {
        try {
            await deleteDoc(doc(db, "widgets", widgetId));
            toast({ title: 'Success', description: 'Widget deleted.' });
            setWidgets(widgets.filter(w => w.id !== widgetId));
        } catch (error) {
            console.error("Error deleting widget:", error);
            toast({ variant: 'destructive', title: 'Error', description: 'Could not delete widget.' });
        }
    }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
            <div>
                <CardTitle className="font-headline">Widgets</CardTitle>
                <CardDescription>Create and manage reusable content blocks for your layouts.</CardDescription>
            </div>
            <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
                <DialogTrigger asChild>
                    <Button size="sm" className="gap-1">
                        <PlusCircle className="h-3.5 w-3.5" />
                        <span className="sr-only sm:not-sr-only sm:whitespace-nowrap">
                        Create Widget
                        </span>
                    </Button>
                </DialogTrigger>
                <DialogContent className="sm:max-w-2xl">
                    <form onSubmit={handleAddWidget}>
                        <DialogHeader>
                        <DialogTitle>Create New Widget</DialogTitle>
                        <DialogDescription>
                            Use AI to generate HTML for a widget, then configure its content source.
                        </DialogDescription>
                        </DialogHeader>
                        <div className="grid gap-6 py-4">
                            <div className="space-y-2">
                                <Label htmlFor="name">Widget Name</Label>
                                <Input id="name" value={newWidgetName} onChange={(e) => setNewWidgetName(e.target.value)} placeholder="e.g., Featured Articles" required />
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="description">Describe the widget layout</Label>
                                <Textarea id="description" value={newWidgetDescription} onChange={(e) => setNewWidgetDescription(e.target.value)} placeholder="e.g., A 3-column grid of cards with a large image, title, and excerpt." required />
                                <Button type="button" variant="outline" size="sm" onClick={handleGenerateHtml} disabled={isGenerating}>
                                    {isGenerating ? <><LoaderCircle className="animate-spin" /> Generating...</> : <><Wand2 className="mr-2 h-4 w-4" /> Generate with AI</>}
                                </Button>
                            </div>
                            
                            <div className="space-y-2">
                                <Label htmlFor="html">Generated HTML</Label>
                                <Textarea id="html" value={newWidgetHtml} onChange={(e) => setNewWidgetHtml(e.target.value)} placeholder="AI-generated HTML will appear here." rows={8} className="font-mono text-xs" required />
                                <p className="text-sm text-muted-foreground">You can manually edit the generated HTML.</p>
                            </div>

                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                <div className="space-y-2">
                                    <Label htmlFor="config-type">Content Source</Label>
                                    <Select value={newWidgetConfigType} onValueChange={(v) => setNewWidgetConfigType(v as any)}>
                                        <SelectTrigger id="config-type"><SelectValue/></SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="category">Category</SelectItem>
                                            <SelectItem value="tag">Tag</SelectItem>
                                        </SelectContent>
                                    </Select>
                                </div>
                                 <div className="space-y-2">
                                    <Label htmlFor="config-value">{newWidgetConfigType === 'category' ? 'Select Category' : 'Enter Tag'}</Label>
                                    {newWidgetConfigType === 'category' ? (
                                        <Select value={newWidgetConfigValue} onValueChange={setNewWidgetConfigValue} required>
                                            <SelectTrigger id="config-value"><SelectValue placeholder={loadingCategories ? 'Loading...' : 'Select a category'} /></SelectTrigger>
                                            <SelectContent>
                                                {categories.map(cat => <SelectItem key={cat.id} value={cat.name}>{cat.name}</SelectItem>)}
                                            </SelectContent>
                                        </Select>
                                    ) : (
                                        <Input id="config-value" value={newWidgetConfigValue} onChange={(e) => setNewWidgetConfigValue(e.target.value)} placeholder="e.g., 'AI'" required/>
                                    )}
                                </div>
                                <div className="space-y-2">
                                    <Label htmlFor="config-limit">Item Limit</Label>
                                    <Input id="config-limit" type="number" value={newWidgetConfigLimit} onChange={(e) => setNewWidgetConfigLimit(parseInt(e.target.value, 10))} min={1} max={20} required/>
                                </div>
                            </div>
                        </div>
                        <DialogFooter>
                            <Button type="button" variant="ghost" onClick={() => setIsDialogOpen(false)}>Cancel</Button>
                            <Button type="submit" disabled={isSaving}>
                                {isSaving ? <><LoaderCircle className="animate-spin" /> Saving...</> : 'Create Widget'}
                            </Button>
                        </DialogFooter>
                    </form>
                </DialogContent>
            </Dialog>
        </div>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Name</TableHead>
              <TableHead>Source</TableHead>
              <TableHead>
                <span className="sr-only">Actions</span>
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {loading ? (
                Array.from({ length: 3 }).map((_, i) => (
                    <TableRow key={i}>
                        <TableCell><Skeleton className="h-4 w-32" /></TableCell>
                        <TableCell><Skeleton className="h-4 w-48" /></TableCell>
                        <TableCell><MoreHorizontal className="h-4 w-4 text-muted-foreground" /></TableCell>
                    </TableRow>
                ))
            ) : widgets.length === 0 ? (
                <TableRow>
                    <TableCell colSpan={3} className="text-center text-muted-foreground py-8">
                        No widgets created yet.
                    </TableCell>
                </TableRow>
            ) : (
                widgets.map((widget) => (
                <TableRow key={widget.id}>
                    <TableCell className="font-medium">{widget.name}</TableCell>
                    <TableCell className="text-muted-foreground capitalize">{widget.config?.type}: {widget.config?.value}</TableCell>
                    <TableCell>
                      <AlertDialog>
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button aria-haspopup="true" size="icon" variant="ghost">
                                <MoreHorizontal className="h-4 w-4" />
                                <span className="sr-only">Toggle menu</span>
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end">
                            <DropdownMenuLabel>Actions</DropdownMenuLabel>
                            <DropdownMenuItem disabled>Edit</DropdownMenuItem>
                             <AlertDialogTrigger asChild>
                                <DropdownMenuItem className="text-destructive" onSelect={(e) => e.preventDefault()}>
                                    <Trash2 className="mr-2 h-4 w-4" />
                                    Delete
                                </DropdownMenuItem>
                            </AlertDialogTrigger>
                          </DropdownMenuContent>
                        </DropdownMenu>
                        <AlertDialogContent>
                            <AlertDialogHeader>
                                <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                                <AlertDialogDescription>
                                This action cannot be undone. This will permanently delete the widget.
                                </AlertDialogDescription>
                            </AlertDialogHeader>
                            <AlertDialogFooter>
                                <AlertDialogCancel>Cancel</AlertDialogCancel>
                                <AlertDialogAction onClick={() => handleDeleteWidget(widget.id)} className="bg-destructive hover:bg-destructive/90">
                                    Yes, delete widget
                                </AlertDialogAction>
                            </AlertDialogFooter>
                        </AlertDialogContent>
                      </AlertDialog>
                    </TableCell>
                </TableRow>
                ))
            )}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  )
}
